
#ifndef RETVAL_HEADER
#define RETVAL_HEADER

enum ReturnValue_t {
	RETVAL_OK = 0,					
	RETVAL_ERROR_GENERAL,
	RETVAL_ERROR_LIMINE_REV,
	RETVAL_ERROR_NO_FRAMEBUFFER,
	RETVAL_ERROR_TEST,	
	RETVAL_ERROR_VIDEOMODE,
	RETVAL_ERROR_NO_FXSAVE,
	RETVAL_ERROR_NO_1GB_PAGES,
	RETVAL_ERROR_NO_GLOBAL_PAGES,
	RETVAL_ERROR_CPUID_LEVEL,
	RETVAL_ERROR_CPUID_EXT_LEVEL,
	RETVAL_ERROR_NO_PAT,
	RETVAL_ERROR_NO_HHDM,
	RETVAL_ERROR_LIMINE_PAGING_MODE,
	RETVAL_ERROR_LIMINE_NULL_POINTER,
	RETVAL_ERROR_PAGE_NOT_FOUND,
	RETVAL_ERROR_PAGE_NOT_PRESENT,
	RETVAL_ERROR_INVALID_PAGELEVEL,
};

#define IS_ERROR(x) ((x) != RETVAL_OK)
#define IS_SUCCESS(x) ((x) == RETVAL_OK)

const char *GetReturnValueString(const ReturnValue_t pReturnValue) __attribute__((const, nothrow));

#endif

